name: Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DOCKER_LOGIN_SECRET }}
      - name: Docker meta Producer
        id: meta-producer
        uses: docker/metadata-action@v3
        with:
          images: us-central1-docker.pkg.dev/apache-kafka-337609/my-docker-registry/producer
          tags: |
            type=ref,event=branch,suffix=-{{sha}},priority=800
            type=ref,event=branch,suffix=-latest
            type=ref,event=tag,priority=1000
      - name: Docker meta Consumer
        id: meta-consumer
        uses: docker/metadata-action@v3
        with:
          images: us-central1-docker.pkg.dev/apache-kafka-337609/my-docker-registry/consumer
          tags: |
            type=ref,event=branch,suffix=-{{sha}},priority=800
            type=ref,event=branch,suffix=-latest
            type=ref,event=tag,priority=1000

      - name: Declare builder Consumer
        id: docker-builder-consumer
        uses: docker/setup-buildx-action@v1
      - name: Declare builder Producer
        id: docker-builder-producer
        uses: docker/setup-buildx-action@v1
      - name: Build and push Consumer
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.docker-builder-consumer.outputs.name }}
          file: consumer/Dockerfile
          push: true
          tags: ${{ steps.meta-consumer.outputs.tags }}
          labels: ${{ steps.meta-consumer.outputs.labels }}
      - name: Build and push Producer
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.docker-builder-producer.outputs.name }}
          file: producer/Dockerfile
          push: true
          tags: ${{ steps.meta-producer.outputs.tags }}
          labels: ${{ steps.meta-producer.outputs.labels }}
